name: CI/CD

on:
  push:
    branches:
      - dev
      - production
      - hotfix/*
      - bugfix/*
      - feature/*
      - dependabot/*
      - main
      - master
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: 'Deploy to production?'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies and build
        run: |
          cd nest
          node -v
          npm ci

      - name: Build Common
        run: |
          cd nest
          npm run build:libs:all

      # CLEAN UP FOR NOW
      # - name: Create artifact archive
      #   run: |
      #     tar -czvf artifact.tar.gz ./nest/node_modules ./nest/dist

      # # move for now to one call for cost effectiveness
      # - name: Run Trivy vulnerability scanner in fs mode
      #   id: trivy_scan
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'
      #     scan-ref: '.'
      #     trivy-config: trivy.yaml
      #     format: 'sarif'
      #     output: 'trivy-results-fs.sarif'
      #     severity: 'CRITICAL,HIGH'
      #     exit-code: 1
      #   continue-on-error: true # This allows the workflow to continue even if this step fails
      #   timeout-minutes: 15

      # - name: Upload Trivy Scan Results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-scan-results
      #     path: trivy-results-fs.sarif

      # - name: Fail if vulnerabilities found
      #   if: ${{ steps.trivy_scan.outcome == 'failure' }}
      #   run: exit 1

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: artifact.tar.gz
